name: Deploy generated.zip to GitHub Pages

on:
  push:
    paths:
      - 'generated.zip'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Calculate SHA1 of generated.zip
      id: hash
      run: |
        HASH=$(sha1sum generated.zip | cut -d ' ' -f1)
        echo "SHA1=$HASH" >> $GITHUB_OUTPUT

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        keep_files: true

    - name: Output download URL and SHA1
      run: |
        echo "::notice title=Pack URL::https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/generated.zip"
        echo "::notice title=SHA1 Hash::${{ steps.hash.outputs.SHA1 }}"
