name: Update Resource Pack and SHA1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Get SHA1 hash of generated.zip
        id: get_sha1
        run: |
          sha1=$(sha1sum generated.zip | awk '{ print $1 }')
          echo "sha1=$sha1" >> $GITHUB_OUTPUT

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy zip to gh-pages
        run: |
          cp generated.zip gh-pages/

      - name: Update index.html with new SHA1
        run: |
          cd gh-pages
          sed -i "s/data-sha1=\"[^"]*\"/data-sha1=\"${{ steps.get_sha1.outputs.sha1 }}\"/g" index.html

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Update resource pack and SHA1 hash" || echo "Nothing to commit"
          git push origin gh-pages
