name: Update Pack Page

on:
  push:
    branches:
      - main
    paths:
      - generated.zip

jobs:
  update-page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate SHA1
        id: sha1
        run: |
          sha1=$(sha1sum generated.zip | awk '{print $1}')
          echo "sha1=$sha1" >> $GITHUB_OUTPUT

      - name: Clone gh-pages branch
        run: |
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages

      - name: Move generated.zip to gh-pages
        run: |
          cp generated.zip gh-pages/

      - name: Update index.html placeholders
        run: |
          sed -i "s|data-sha1=\"[^"]*\"|data-sha1=\"${{ steps.sha1.outputs.sha1 }}\"|g" gh-pages/index.html
          sed -i "s|data-url=\"[^"]*\"|data-url=\"https://$GITHUB_REPOSITORY_OWNER.github.io/${{ github.event.repository.name }}/generated.zip\"|g" gh-pages/index.html

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add generated.zip index.html
          git diff --cached --quiet || git commit -m "Update generated.zip and SHA1"
          git push
