name: Update Resource Pack

on:
  push:
    branches:
      - main
    paths:
      - 'generated.zip'

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate SHA1 of generated.zip
        id: sha
        run: |
          sha1=$(sha1sum generated.zip | awk '{ print $1 }')
          echo "SHA1=$sha1" >> $GITHUB_OUTPUT

      - name: Clone gh-pages branch
        run: |
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages

      - name: Copy updated generated.zip
        run: |
          cp generated.zip gh-pages/

      - name: Replace placeholders in index.html
        run: |
          cd gh-pages
          sed -i "s|__SHA1_HASH__|${{ steps.sha.outputs.SHA1 }}|g" index.html
          sed -i "s|__PACK_URL__|https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/generated.zip|g" index.html

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.html generated.zip
          git commit -m "Update resource pack and SHA1 hash" || echo "No changes to commit"
          git push origin gh-pages
