name: Update SHA1 and Upload Pack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate SHA1 hash
      run: |
       sha1=$(sha1sum generated.zip | cut -d ' ' -f1)
       echo "SHA1=$sha1" >> $GITHUB_ENV
    - name: Clone gh-pages branch
      run: git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages

    - name: Copy resource pack and update HTML
      run: |
        cp generated.zip gh-pages/generated.zip
        sed -i "s/SHA1 : .*/SHA1 : $SHA1/" gh-pages/index.html

    - name: Commit and push changes
      run: |
        cd gh-pages
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Update resource pack and SHA1 hash" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:gh-pages
