name: Update SHA1 and HTML

on:
  push:
    branches: [main]
    paths:
      - generated.zip

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for GH Pages

      - name: Calculate SHA1
        id: hash
        run: |
          sha1=$(sha1sum generated.zip | awk '{print $1}')
          echo "SHA1=$sha1"
          echo "sha1=$sha1" >> $GITHUB_OUTPUT

      - name: Debug: Show current placeholder state
        run: |
          echo "== BEFORE =="
          cat gh-pages/index.html

      - name: Replace SHA1 placeholder in HTML
        run: |
          sed -i "s|SHA1: PLACEHOLDER|SHA1: ${SHA1}|" gh-pages/index.html
        env:
          SHA1: ${{ steps.hash.outputs.sha1 }}

      - name: Debug: Show updated HTML
        run: |
          echo "== AFTER =="
          cat gh-pages/index.html

      - name: Commit & Push updated HTML
        run: |
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git diff --quiet && echo "No changes to commit" || (git commit -m "Update SHA1 in HTML" && git push)
