name: Update SHA1 and HTML

on:
  push:
    branches:
      - main
    paths:
      - 'generated.zip'

permissions:
  contents: write

jobs:
  update-sha1-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate SHA1
        id: sha1
        run: echo "sha1=$(sha1sum generated.zip | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"

      - name: Checkout GH Pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update HTML with new SHA1
        run: |
          sed -i "s/PLACEHOLDER/${{ steps.sha1.outputs.sha1 }}/g" gh-pages/index.html

      - name: Commit and push updated HTML
        run: |
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Update SHA1 in HTML"
          git push
