name: Upload Resource Pack and Update SHA1

on:
  push:
    branches:
      - main
    paths:
      - generated.zip

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate SHA1
        id: sha
        run: echo "sha1=$(sha1sum generated.zip | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Clone gh-pages branch
        run: |
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          cp generated.zip gh-pages/
          cd gh-pages
          sed -i "s|<span id=\"sha1\">.*</span>|<span id=\"sha1\">${{ steps.sha.outputs.sha1 }}</span>|g" index.html
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update resource pack and SHA1 hash" || echo "No changes to commit"
          git push
