name: Update GitHub Pages with Resource Pack

on:
  push:
    branches:
      - main
    paths:
      - 'generated.zip'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Calculate SHA1
        id: sha
        run: |
          echo "SHA1=$(sha1sum generated.zip | awk '{ print $1 }')" >> $GITHUB_OUTPUT

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy files to gh-pages
        run: |
          cp generated.zip gh-pages/generated.zip

      - name: Update index.html SHA1 + URL
        run: |
          cd gh-pages
          sed -i "s|__SHA1_HASH__|${{ steps.sha.outputs.SHA1 }}|g" index.html
          sed -i "s|__PACK_URL__|https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/generated.zip|g" index.html

      - name: Commit and push
        run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update generated.zip and SHA1" || echo "No changes"
          git push origin gh-pages
