name: Update SHA1 in HTML

on:
  push:
    branches:
      - main
    paths:
      - generated.zip

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: true

      - name: Download generated.zip from main
        run: |
          wget https://raw.githubusercontent.com/r-pixie/minecraft-resourcepack/main/generated.zip -O generated.zip

      - name: Calculate SHA1 hash
        id: hash
        run: |
          sha1=$(sha1sum generated.zip | awk '{print $1}')
          echo "sha1=$sha1" >> $GITHUB_OUTPUT

      - name: Update SHA1 in index.html
        run: |
          sed -i "s|data-sha1=\"[^\"]*\"|data-sha1=\"${{ steps.hash.outputs.sha1 }}\"|g" index.html
          sed -i "s|const sha1 = \".*\"|const sha1 = \"${{ steps.hash.outputs.sha1 }}\"|g" index.html

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Update SHA1 in HTML"
          git push origin gh-pages
