name: Upload Resource Pack and Update HTML

on:
  push:
    branches:
      - main
    paths:
      - generated.zip

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Calculate SHA1 of generated.zip
        id: sha
        run: |
          echo "sha1=$(sha1sum generated.zip | awk '{ print $1 }')" >> $GITHUB_OUTPUT

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy new resource pack
        run: |
          cp generated.zip gh-pages/generated.zip

      - name: Update index.html with SHA1 and URL
        working-directory: gh-pages
        run: |
          ZIP_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/generated.zip"
          sed -i "s|__PACK_URL__|$ZIP_URL|g" index.html
          sed -i "s|__SHA1_HASH__|${{ steps.sha.outputs.sha1 }}|g" index.html

      - name: Commit and push
        run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add generated.zip index.html
          git commit -m "Update resource pack and SHA1" || echo "No changes to commit"
          git push
