name: Update SHA1 in HTML

on:
  push:
    paths:
      - 'generated.zip'

jobs:
  update-sha1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Calculate SHA1
        id: sha
        run: echo "sha1=$(sha1sum generated.zip | cut -d ' ' -f1)" >> $GITHUB_OUTPUT

      - name: Update HTML
        run: |
          sed -i "s|data-sha1=\"[^\"]*\"|data-sha1=\"${{ steps.sha.outputs.sha1 }}\"|g" gh-pages/index.html
          sed -i "s|const sha1 = \".*\"|const sha1 = \"${{ steps.sha.outputs.sha1 }}\"|g" gh-pages/index.html

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update SHA1 in HTML"
