name: Update SHA1 in HTML

on:
  push:
    branches: [main]
    paths:
      - "generated.zip"

jobs:
  update-sha1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Generate SHA1 hash
        id: sha
        run: |
          HASH=$(sha1sum generated.zip | awk '{ print $1 }')
          echo "SHA1=$HASH" >> $GITHUB_ENV
          echo "Generated SHA1: $HASH"

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update HTML with SHA1
        run: |
          sed -i "s/PLACEHOLDER/$SHA1/g" gh-pages/index.html

      - name: Commit & Push updated HTML
        run: |
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Update SHA1 in HTML"
          git push
